function fillMenu() {
    return [
        new MenuItem('PB & J', 5.95, 'Breakfast', 'Sandwich'),
        new MenuItem('Egg & Cheese', 5.25, 'Breakfast', 'Sandwich'),
        new MenuItem('Ham, Egg & Cheese', 5.75, 'Breakfast', 'Sandwich'),
        new MenuItem('Bacon, Egg & Cheese', 5.75, 'Breakfast', 'Sandwich'),
        new MenuItem('Egg, Avocado & Cheese', 5.75, 'Breakfast', 'Sandwich'),
        new MenuItem('Ham, Bacon, Egg & Cheese', 5.95, 'Breakfast', 'Sandwich'),

        new MenuItem('Ham, Bacon, Egg & Cheese', 5.95, 'Breakfast', 'Burrito'),
        new MenuItem('Chorizo, Egg & Cheese', 5.95, 'Breakfast', 'Burrito'),

        new MenuItem('Nachos', 5.95, 'Lunch', 'Mexican'),
        new MenuItem('Nachos Grande', 8.95, 'Lunch', 'Mexican'),
        new MenuItem('Tostada w/ Guacamole', 5.95, 'Lunch', 'Mexican'),
        new MenuItem('Tostada w/ Beef', 6.95, 'Lunch', 'Mexican'),
        new MenuItem('Cheese Quesadilla', 6.95, 'Lunch', 'Mexican'),
        new MenuItem('Chicken Quesadilla', 9.95, 'Lunch', 'Mexican'),
        new MenuItem('Beef Quesadilla', 9.95, 'Lunch', 'Mexican'),

        new MenuItem('Ham', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Roast Beef', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Pastrami', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Veggie', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Tuna', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('French Dip', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Italian Submarine', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey & Ham', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Clubhouse', 9.95, 'Lunch', 'Sandwich'),
        new MenuItem('Meatball', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('BLT', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('BBQ Beef', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('BBQ Ham', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey Bacon', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Salami', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Pastrami Dip', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey & Avocado', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey Bacon Melt', 9.25, 'Lunch', 'Sandwich'),
        new MenuItem('Turkey & Bacon Ranch', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Tuna Salad', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Tuna Melt', 8.50, 'Lunch', 'Sandwich'),
        new MenuItem('Egg Salad', 8.25, 'Lunch', 'Sandwich'),
        new MenuItem('Roast Beef Cheddar Melt', 9.25, 'Lunch', 'Sandwich'),
        new MenuItem('Shredded Beef Torta', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('California Club', 9.95, 'Lunch', 'Sandwich'),
        new MenuItem('Grilled Chicken', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Teriyaki Chicken', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Chicken Club', 9.95, 'Lunch', 'Sandwich'),
        new MenuItem('Chicken Salad', 9.95, 'Lunch', 'Sandwich'),
        new MenuItem('BBQ Chicken', 8.95, 'Lunch', 'Sandwich'),
        new MenuItem('Pastrami Ruben', 9.95, 'Lunch', 'Sandwich'),

        new MenuItem('Bomber Burger', 8.95, 'Lunch', 'Burger', true),
        new MenuItem('Avocado Burger', 7.95, 'Lunch', 'Burger', true),
        new MenuItem('Pastrami Burger', 7.95, 'Lunch', 'Burger', true),
        new MenuItem('Jalapeño Burger', 7.95, 'Lunch', 'Burger', true),
        new MenuItem('Bacon Cheese Burger', 7.95, 'Lunch', 'Burger', true),
        new MenuItem('Cheese Burger', 6.95, 'Lunch', 'Burger', true),

        new MenuItem('Chef Salad', 8.25, 'Lunch', 'Salad'),
        new MenuItem('Tuna Salad', 8.25, 'Lunch', 'Salad'),
        new MenuItem('Grilled Chicken Salad', 8.25, 'Lunch', 'Salad'),
        new MenuItem('Tossed Salad', 7.95, 'Lunch', 'Salad'),
    ]
}